# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfeedback',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read'), ('deleted', 'deleted')], default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='generalfeedback',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
