# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signfeedback',
            old_name='link',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='missingsignfeedback',
            name='handform',
            field=models.IntegerField(blank=True, choices=[(0, None), (1, 'One handed'), (2, 'Two handed (same shape for each hand)'), (3, 'Two handed (diffent shapes for each hand)')], default=0),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='comment',
            field=models.TextField(verbose_name='Please give us your comments about this sign. For example: do you think there are other keywords that belong with this sign? Please write your comments or new keyword/s below.'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='correct',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'Mostly Correct'), (3, "Don't Know"), (4, 'Mostly Wrong'), (5, 'No'), (0, 'N/A')], default=0, verbose_name='Is the information about the sign correct?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='isAuslan',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'Perhaps'), (3, "Don't know"), (4, "Don't think so"), (5, 'No'), (0, 'N/A')], default=0, verbose_name='Is this sign an Auslan language Sign?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='like',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'A little'), (3, "Don't care"), (4, 'Not much'), (5, 'No'), (0, 'N/A')], default=0, verbose_name='Do you like this sign?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='whereused',
            field=models.CharField(choices=[('auswide', 'Australia Wide'), ('dialectN', 'Dialect Sign (North)'), ('dialectS', 'Dialect Sign (South)'), ('nsw', 'New South Wales'), ('vic', 'Victoria'), ('qld', 'Queensland'), ('wa', 'Western Australia'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('nt', 'Northern Territory'), ('act', 'Australian Capital Territory'), ('dk', "Don't Know"), ('n/a', 'N/A')], default='n/a', max_length=10, verbose_name='Where is this sign used?'),
        ),
    ]
