# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20161015_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='signfeedback',
            name='kind',
            field=models.TextField(default='word'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='correct',
            field=models.IntegerField(blank=True, choices=[(1, 'yes'), (2, 'Mostly Correct'), (3, "Don't Know"), (4, 'Mostly Wrong'), (5, 'No'), (0, 'N/A')], default=0, verbose_name='Is the information about the sign correct?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='isAuslan',
            field=models.IntegerField(blank=True, choices=[(1, 'yes'), (2, 'Perhaps'), (3, "Don't know"), (4, "Don't think so"), (5, 'No'), (0, 'N/A')], default=0, verbose_name='Is this sign an Auslan language Sign?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='like',
            field=models.IntegerField(blank=True, choices=[(1, 'yes'), (2, 'A little'), (3, "Don't care"), (4, 'Not much'), (5, 'No'), (0, 'N/A')], default=0, verbose_name='Do you like this sign?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='suggested',
            field=models.IntegerField(blank=True, choices=[(1, 'yes'), (2, 'Sometimes'), (3, "Don't Know"), (4, 'Perhaps'), (5, 'No'), (0, 'N/A')], default=3, verbose_name='If this sign is a suggested new sign, would you use it?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='use',
            field=models.IntegerField(blank=True, choices=[(1, 'yes'), (2, 'Sometimes'), (3, 'Not Often'), (4, 'No'), (0, 'N/A')], default=0, verbose_name='Do you use this sign?'),
        ),
        migrations.AlterField(
            model_name='signfeedback',
            name='whereused',
            field=models.CharField(blank=True, choices=[('auswide', 'Australia Wide'), ('dialectN', 'Dialect Sign (North)'), ('dialectS', 'Dialect Sign (South)'), ('nsw', 'New South Wales'), ('vic', 'Victoria'), ('qld', 'Queensland'), ('wa', 'Western Australia'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('nt', 'Northern Territory'), ('act', 'Australian Capital Territory'), ('dk', "Don't Know"), ('n/a', 'N/A')], default='n/a', max_length=10, verbose_name='Where is this sign used?'),
        ),
    ]
