# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_missingsignfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('word', models.TextField()),
                ('comment', models.TextField(blank=True, verbose_name='Please give us your comments about this sign. For example: do you think there are other keywords that belong with this sign? Please write your comments or new keyword/s below.')),
                ('kwnotbelong', models.TextField(blank=True, verbose_name='Is there a keyword or keyword/s that DO NOT belong with this sign? Please provide the list of keywords below')),
                ('isAuslan', models.IntegerField(choices=[(1, 'yes'), (2, 'Perhaps'), (3, "Don't know"), (4, "Don't think so"), (5, 'No'), (0, 'N/A')], verbose_name='Is this sign an Auslan language Sign?')),
                ('whereused', models.CharField(choices=[('auswide', 'Australia Wide'), ('dialectN', 'Dialect Sign (North)'), ('dialectS', 'Dialect Sign (South)'), ('nsw', 'New South Wales'), ('vic', 'Victoria'), ('qld', 'Queensland'), ('wa', 'Western Australia'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('nt', 'Northern Territory'), ('act', 'Australian Capital Territory'), ('dk', "Don't Know"), ('n/a', 'N/A')], max_length=10, verbose_name='Where is this sign used?')),
                ('like', models.IntegerField(choices=[(1, 'yes'), (2, 'A little'), (3, "Don't care"), (4, 'Not much'), (5, 'No'), (0, 'N/A')], verbose_name='Do you like this sign?')),
                ('use', models.IntegerField(choices=[(1, 'yes'), (2, 'Sometimes'), (3, 'Not Often'), (4, 'No'), (0, 'N/A')], verbose_name='Do you use this sign?')),
                ('suggested', models.IntegerField(choices=[(1, 'yes'), (2, 'Sometimes'), (3, "Don't Know"), (4, 'Perhaps'), (5, 'No'), (0, 'N/A')], default=3, verbose_name='If this sign is a suggested new sign, would you use it?')),
                ('correct', models.IntegerField(choices=[(1, 'yes'), (2, 'Mostly Correct'), (3, "Don't Know"), (4, 'Mostly Wrong'), (5, 'No'), (0, 'N/A')], verbose_name='Is the information about the sign correct?')),
                ('status', models.CharField(choices=[('unread', 'unread'), ('read', 'read'), ('deleted', 'deleted')], default='unread', max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
