# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_signfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signfeedback',
            old_name='word',
            new_name='link',
        ),
    ]
